version: '3.8'

services:
  db:
    image: mariadb:10.9
    volumes:
      - ./dbdata:/var/lib/mysql
      - ./config/db:/etc/mysql/conf.d
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MARIADB_ROOT_HOST=%
      - MARIADB_ROOT_PASSWORD=$MARIADB_ROOT_PASSWORD
      - MARIADB_DATABASE=$WORDPRESS_DB_NAME
      - MARIADB_USER=$WORDPRESS_DB_USER
      - MARIADB_PASSWORD=$WORDPRESS_DB_PASSWORD
    ports:
      - 3306:3306
    networks:
      - wp-network

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=$MARIADB_ROOT_PASSWORD
      - UPLOAD_LIMIT=300M
    depends_on:
      - db
    networks:
      - wp-network
    ports:
      - '20080:80'

  wordpress:
    image: wordpress:php8.0-fpm-alpine
    depends_on:
      - db
    # ports:
    #   - 80:80
    restart: always
    env_file: .env
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=$WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD=$WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME=$WORDPRESS_DB_NAME
    volumes:
      - wordpress_resource:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - wp-network

  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    ports:
      - 80:80
      - 443:443
    volumes:
      - wordpress_resource:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./config/certs:/etc/nginx/certs
    restart: always
    networks:
      - wp-network

volumes:
  wordpress_resource: #/resource

# Define toolbox network
networks:
  wp-network:
    driver: bridge